### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by yumianhuli1** [PKU-YuanGroup/Video-LLaVA#100]
Hello！

Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:06<00:00,  3.17s/it]
Some weights of the model checkpoint at model were not used when initializing LlavaLlamaForCausalLM: ['model.image_tower.image_tower.encoder.layers.15.self_attn.k_proj.weight', 'model.video_tower.video_tower.encoder.layers.15.mlp.fc1.weight', 'model.image_tower.image_tower.encoder.layers.17.layer_norm1.bias', 'model.image_tower.image_tower.encoder.layers.7.layer_norm2.weight', 'model.video_tower.video_tower.encoder.layers.22.self_attn.q_proj.weight', 'model.video_tower.video_tower.encoder.layers.10.self_attn.k_proj.weight', 'model.image_tower.image_tower.encoder.layers.11.self_attn.k_proj.weight', 'model.video_tower.video_tower.encoder.layers.9.self_attn.q_proj.weight', 'model.video_tower.video_tower.encoder.layers.11.temporal_attn.v_proj.bias', 
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
'model.video_tower.video_tower.encoder.layers.23.mlp.fc1.bias', 
'model.image_tower.image_tower.encoder.layers.13.layer_norm1.weight', 'model.video_tower.video_tower.encoder.layers.11.layer_norm1.bias']
- This IS expected if you are initializing LlavaLlamaForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LlavaLlamaForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "/home/win11/githubPublic/text-generation-webui/installer_files/conda/envs/videollava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/win11/githubPublic/text-generation-webui/installer_files/conda/envs/videollava/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/win11/Documents/Video-LLaVA/videollava/serve/cli.py", line 135, in <module>
    main(args)
  File "/home/win11/Documents/Video-LLaVA/videollava/serve/cli.py", line 62, in main
    file = video_processor(file, return_tensors='pt')['pixel_values'][0].to(model.device, dtype=torch.float16)
TypeError: 'NoneType' object is not callable

It seems to have read the model correctly, But when exec tokenizer, model, processor, _ = load_pretrained_model(model_path, None, model_name, load_8bit, When load_4bit,device=device, cache_dir=cache_dir), processor returns empty

**Comment by HosamGen** [comment]
Did you happen to fix this? I am actually having the same issue.

**Comment by yumianhuli1** [comment]
> Did you happen to fix this? I am actually having the same issue.

no

**Comment by HosamGen** [comment]
I think if you put the word "llava" in your model checkpoint name it should work, I tried debugging it and that was the only solution that worked for me.

**Comment by wyk123wyk** [comment]
Did you happen to fix this? I am actually having the same issue.

**Comment by wyk123wyk** [comment]
@HosamGen Can you explain it in more detail？Thanks！

**Comment by HosamGen** [comment]
@wyk123wyk Its been a while but I believe the "model_path" you pass while running the inference must contain the word "llava" in it.

**Comment by wyk123wyk** [comment]
@HosamGen ，It‘s really useful，thanks！But that’s so magic that I can't understand.
