### ISSUE TITLE
Transformer version

### ISSUE THREAD

**Issue by apurvgandhwani** [PKU-YuanGroup/Video-LLaVA#119]
Hi

```
from transformers import AutoModel

model_name = "LanguageBind/Video-LLaVA-7B"
model = AutoModel.from_pretrained(model_name)
```

When I am trying to run this, I am getting the error 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/.local/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers.models.llava.configuration_llava.LlavaConfig'> for this kind of AutoModel: AutoModel.
```

I have following versions installed on my machine

torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 transformers==4.38.1

**Comment by notahuman-1-0** [comment]
Please install transformers==4.31
