### ISSUE TITLE
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/workspace/llm/weight_files/Video-LLaVA-7B'. Use `repo_type` argument if needed.

### ISSUE THREAD

**Issue by HAOYON-666** [PKU-YuanGroup/Video-LLaVA#209]
When I use this code to load the local model for inference, it doesn't work properly

    import torch
    from videollava.constants import IMAGE_TOKEN_INDEX, DEFAULT_IMAGE_TOKEN
    from videollava.conversation import conv_templates, SeparatorStyle
    from videollava.model.builder import load_pretrained_model
    from videollava.utils import disable_torch_init
    from videollava.mm_utils import tokenizer_image_token, get_model_name_from_path, KeywordsStoppingCriteria
    
    def main():
        disable_torch_init()
        image = './videollava/serve/examples/extreme_ironing.jpg'
        inp = 'What is unusual about this image?'
        model_path = '/data/workspace/llm/weight_files/Video-LLaVA-7B'
        cache_dir = '/data/workspace/llm/weight_files/Video-LLaVA-7B'
        device = 'cuda'
        load_4bit, load_8bit = True, False
        model_name = get_model_name_from_path(model_path)
        tokenizer, model, processor, _ = load_pretrained_model(model_path, None, model_name, load_8bit, load_4bit, device=device, cache_dir=cache_dir)
        image_processor = processor['image']
        conv_mode = "llava_v1"
        conv = conv_templates[conv_mode].copy()
        roles = conv.roles
    
        image_tensor = image_processor.preprocess(image, return_tensors='pt')['pixel_values']
        if type(image_tensor) is list:
            tensor = [image.to(model.device, dtype=torch.float16) for image in image_tensor]
        else:
            tensor = image_tensor.to(model.device, dtype=torch.float16)
    
        print(f"{roles[1]}: {inp}")
        inp = DEFAULT_IMAGE_TOKEN + '\n' + inp
        conv.append_message(conv.roles[0], inp)
        conv.append_message(conv.roles[1], None)
        prompt = conv.get_prompt()
        input_ids = tokenizer_image_token(prompt, tokenizer, IMAGE_TOKEN_INDEX, return_tensors='pt').unsqueeze(0).cuda()
        stop_str = conv.sep if conv.sep_style != SeparatorStyle.TWO else conv.sep2
        keywords = [stop_str]
        stopping_criteria = KeywordsStoppingCriteria(keywords, tokenizer, input_ids)
    
        with torch.inference_mode():
            output_ids = model.generate(
                input_ids,
                images=tensor,
                do_sample=True,
                temperature=0.2,
                max_new_tokens=1024,
                use_cache=True,
                stopping_criteria=[stopping_criteria])
    
        outputs = tokenizer.decode(output_ids[0, input_ids.shape[1]:]).strip()
        print(outputs)
    
    if __name__ == '__main__':
        main()

**Comment by HAOYON-666** [comment]
/home/user/miniconda3/envs/videollava/lib/python3.10/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
/home/user/miniconda3/envs/videollava/lib/python3.10/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
/home/user/miniconda3/envs/videollava/lib/python3.10/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "/data/workspace/zhaoyong/model/Video-LLaVA/infer.py", line 107, in <module>
    main()
  File "/data/workspace/zhaoyong/model/Video-LLaVA/infer.py", line 71, in main
    tokenizer, model, processor, _ = load_pretrained_model(model_path, None, model_name, load_8bit, load_4bit, device=device, cache_dir=cache_dir)
  File "/data/workspace/zhaoyong/model/Video-LLaVA/videollava/model/builder.py", line 107, in load_pretrained_model
    tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
  File "/home/user/miniconda3/envs/videollava/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 652, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/home/user/miniconda3/envs/videollava/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 496, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/home/user/miniconda3/envs/videollava/lib/python3.10/site-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "/home/user/miniconda3/envs/videollava/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/user/miniconda3/envs/videollava/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/workspace/zhaoyong/llm/weight_files/Video-LLaVA-7B'. Use `repo_type` argument if needed.
