### ISSUE TITLE
Finetuneing on 4xA6000 (48G)

### ISSUE THREAD

**Issue by orrzohar** [PKU-YuanGroup/Video-LLaVA#66]
Hi,
I got the following when trying to finetune:

```
DATA_ROOT="data"
HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1 CUDA_VISIBLE_DEVICES=0,1,2,3 deepspeed llava/train/train_mem.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path lmsys/vicuna-7b-v1.5 \
    --version v1 \
    --data_path train_json/videochatgpt_llavaimage_tune.json \
    --video_folder ${DATA_ROOT} \
    --image_folder ${DATA_ROOT} \
    --X "Video" "Image" \
    --video_tower LanguageBind/LanguageBind_Video_merge \
    --image_tower LanguageBind/LanguageBind_Image \
    --pretrain_mm_mlp_adapter checkpoints/Video-LLaVA-Pretrain-7B/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_x_start_end False \
    --mm_use_x_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/Video-LLaVA-7B \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to tensorboard \
    --cache_dir "./cache_dir"
```

 with 4xA6000s:
 
 (...standard printing of model...)
 ```
cpu
Rank: 1 partition count [4, 4] and sizes[(1689846784, False), (2048, False)] 
Rank: 0 partition count [4, 4] and sizes[(1689846784, False), (2048, False)] 
Rank: 3 partition count [4, 4] and sizes[(1689846784, False), (2048, False)] 
Rank: 2 partition count [4, 4] and sizes[(1689846784, False), (2048, False)] 
[2024-01-06 11:50:49,968] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 2867800
[2024-01-06 11:50:50,170] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 2867801
[2024-01-06 11:50:50,359] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 2867802
[2024-01-06 11:50:50,362] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 2867803
[2024-01-06 11:50:50,919] [ERROR] [launch.py:321:sigkill_handler] ['/pasteur/u/orrzohar/miniconda3/envs/videollava/bin/python', '-u', 'llava/train/train_mem.py', '--local_rank=3', '--deepspeed', './scripts/zero2.json', '--model_name_or_path', 'lmsys/vicuna-7b-v1.5', '--version', 'v1', '--data_path', 'train_json/videochatgpt_llavaimage_tune.json', '--video_folder', 'data', '--image_folder', 'data', '--X', 'Video', 'Image', '--video_tower', 'LanguageBind/LanguageBind_Video_merge', '--image_tower', 'LanguageBind/LanguageBind_Image', '--pretrain_mm_mlp_adapter', 'checkpoints/Video-LLaVA-Pretrain-7B/mm_projector.bin', '--mm_projector_type', 'mlp2x_gelu', '--mm_vision_select_layer', '-2', '--mm_use_x_start_end', 'False', '--mm_use_x_patch_token', 'False', '--image_aspect_ratio', 'pad', '--group_by_modality_length', 'True', '--bf16', 'True', '--output_dir', './checkpoints/Video-LLaVA-7B', '--num_train_epochs', '1', '--per_device_train_batch_size', '1', '--per_device_eval_batch_size', '1', '--gradient_accumulation_steps', '2', '--evaluation_strategy', 'no', '--save_strategy', 'steps', '--save_steps', '50000', '--save_total_limit', '1', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--lr_scheduler_type', 'cosine', '--logging_steps', '1', '--tf32', 'True', '--model_max_length', '2048', '--gradient_checkpointing', 'True', '--dataloader_num_workers', '4', '--lazy_preprocess', 'True', '--report_to', 'tensorboard', '--cache_dir', './cache_dir'] exits with return code = 1
```

The error is of "out of memory":
```
torch.cuda.OutOfMemoryErrortorch.cuda: .torch.cudaCUDA out of memory. Tried to allocate 6.30 GiB (GPU 2; 47.54 GiB total capacity; 45.45 GiB already allocated; 1.49 GiB free; 45.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONFOutOfMemoryError.
: OutOfMemoryErrorCUDA out of memory. Tried to allocate 6.30 GiB (GPU 1; 47.54 GiB total capacity; 45.45 GiB already allocated; 1.49 GiB free; 45.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF: 
CUDA out of memory. Tried to allocate 6.30 GiB (GPU 3; 47.54 GiB total capacity; 45.45 GiB already allocated; 1.56 GiB free; 45.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/pasteur/u/orrzohar/LLAQA/VL/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/pasteur/u/orrzohar/LLAQA/Video-LLaVA/llava/train/train.py", line 1060, in train
    trainer.train()
  File "/pasteur/u/orrzohar/miniconda3/envs/videollava/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/pasteur/u/orrzohar/miniconda3/envs/videollava/lib/python3.10/site-packages/transformers/trainer.py", line 1656, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/pasteur/u/orrzohar/miniconda3/envs/videollava/lib/python3.10/site-packages/accelerate/accelerator.py", line 1198, in prepare
    result = self._prepare_deepspeed(*args)
  File "/pasteur/u/orrzohar/miniconda3/envs/videollava/lib/python3.10/site-packages/accelerate/accelerator.py", line 1537, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/pasteur/u/orrzohar/miniconda3/envs/videollava/lib/python3.10/site-packages/deepspeed/__init__.py", line 165, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/pasteur/u/orrzohar/miniconda3/envs/videollava/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 309, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/pasteur/u/orrzohar/miniconda3/envs/videollava/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1184, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/pasteur/u/orrzohar/miniconda3/envs/videollava/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1419, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/pasteur/u/orrzohar/miniconda3/envs/videollava/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 484, in __init__
    self.initialize_optimizer_states()
  File "/pasteur/u/orrzohar/miniconda3/envs/videollava/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 619, in initialize_optimizer_states
    self.optimizer.step()
  File "/pasteur/u/orrzohar/miniconda3/envs/videollava/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
  File "/pasteur/u/orrzohar/miniconda3/envs/videollava/lib/python3.10/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/pasteur/u/orrzohar/miniconda3/envs/videollava/lib/python3.10/site-packages/torch/optim/optimizer.py", line 33, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/pasteur/u/orrzohar/miniconda3/envs/videollava/lib/python3.10/site-packages/torch/optim/adamw.py", line 171, in step
    adamw(
  File "/pasteur/u/orrzohar/miniconda3/envs/videollava/lib/python3.10/site-packages/torch/optim/adamw.py", line 321, in adamw
    func(
  File "/pasteur/u/orrzohar/miniconda3/envs/videollava/lib/python3.10/site-packages/torch/optim/adamw.py", line 566, in _multi_tensor_adamw
    denom = torch._foreach_add(exp_avg_sq_sqrt, eps)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.30 GiB (GPU 0; 47.54 GiB total capacity; 45.45 GiB already allocated; 1.50 GiB free; 45.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

This is after I tried reducing the batch size from 16 to 1 (currently just trying to get it to finetune in general) - in line with issue https://github.com/PKU-YuanGroup/Video-LLaVA/issues/45

Best,
Orr

**Comment by LinB203** [comment]
Currently a lot of people are giving feedback on OOM, however I'm not having this problem by re-pulling the code. I'm speculating that there may be a difference in the system environment. I am trying to resolve this issue.

**Comment by LinB203** [comment]
I uploaded `zero2_offload.json`, you can try `--deepspeed . /scripts/zero2_offload.json`, feel free to let me know of any updates.

**Comment by LinB203** [comment]
Hi, we reorganize the code and support LoRA fine-tuning, checking [finetune_lora.sh](https://github.com/PKU-YuanGroup/Video-LLaVA/blob/main/scripts/v1_5/finetune_lora.sh).

**Comment by orrzohar** [comment]
Hi @LinB203,
How does LoRA performance compare? is there a noticeable difference in performance?
Best,
Orr

**Comment by orrzohar** [comment]
Note for future people; 
I have managed to run this on 8XA6000.

**Comment by YoungjaeDev** [comment]
@orrzohar 
Is this enough to cover 4 RTX3090s?

**Comment by amajee11us** [comment]
@orrzohar Can you please share your configs ?
I am interested to run both the pre-training and the instruction tuning steps on 8x A6000s.
